project1/music/urls.py
from django.conf.urls import url
from . import views 
app_name = 'music'

urlpatterns = [
    #/music/
    #url(r'^$', views.index, name='index'),
    url(r'^album$', views.IndexView.as_view(), name='index'),
    url(r'^$', views.IndexView.as_view(), name='index'),

    #/music/<album_id>
    url(r'^(?P<pk>[0-9]+)/$', views.DetailsView.as_view(), name='details'),

    # /music/album/add/
    url(r'album/add/$', views.AlbumCreate.as_view(), name='album-add'),
    # /music/album/id/
    url(r'album/(?P<pk>[0-9]+)/$', views.AlbumUpdate.as_view(), name='album-update'),
    # /music/album/pk/delete
    url(r'album/(?P<pk>[0-9]+)/delete/$', views.AlbumDelete.as_view(), name='album-delete'),

    # Authenticate
    url(r'^register$', views.UserFormView.as_view(), name='register'),

];

project1/project1/urls.py
from django.contrib import admin
from django.conf.urls import url, include

from rest_framework.urlpatterns import format_suffix_patterns
from stock import views


urlpatterns = [
    url('admin/', admin.site.urls),
    url(r'^$', include('posts.urls')),
    url(r'^posts/', include('posts.urls')),
    url(r'^music/', include('music.urls')),
    url(r'^stock/', views.StockList.as_view()),
    url(r'^ApiGeo/', include('ApiGeo.urls')),
    url('accounts/', include('django.contrib.auth.urls'))
]

urlpatterns = format_suffix_patterns(urlpatterns)

project1/music/models.py
import string

from django.db import models
from django.urls import reverse


class Album(models.Model):
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=500)
    genre = models.CharField(max_length=100)
    album_logo = models.CharField(max_length=1000)
    
    def get_absolute_url(self):
        return reverse('music:details', kwargs={'pk':self.pk})

    def __str__(self):
        return self.album_title+' - '+self.artist


class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    song_title = models.CharField(max_length=250)
    is_fav = models.BooleanField(default=False)

    def __str__(self):
        return self.song_title


class Animal:
    name = string
    size = int
    sound = string

    def __init__(self, name, size, sound):
        self.name = name
        self.size = size
        self.sound = sound

    def speak(self, s):
        return "The "+str(self.name)+ " says "+s

project1/music/views.py
from django.views import generic 
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Album
from django.urls import reverse_lazy

from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.views.generic import View
from .form import UserForm
from django.http import HttpResponse
from django.contrib.auth.mixins import LoginRequiredMixin


class IndexView(LoginRequiredMixin, generic.ListView):
    login_url = '/login'
    redirect_field_name = '/'
    template_name = 'music/index.html' 
    context_object_name = 'all_albums'

    def get_queryset(self):
        return Album.objects.all()

class DetailsView(generic.DetailView):
    model = Album
    template_name = 'music/details.html'

class AlbumCreate(CreateView):
    model = Album
    fields = ['artist', 'album_title', 'genre', 'album_logo']

class AlbumUpdate(UpdateView):
    model = Album
    fields = ['artist', 'album_title', 'genre', 'album_logo']

class AlbumDelete(DeleteView):
    model = Album
    success_url = reverse_lazy('music:index')

class UserFormView(View):
    # It is the blue print u use for ur form
    form_class = UserForm
    template_name = 'music/registration_form.html'

    # Display a blank form
    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})
        
    # process form data    
    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():
            user = form.save(commit=False)
            #cleaned (normalized) data
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            
            #user.password = 'chicken_and_run' we can't write the pw like this bcause of the hash code
            #proper way :
            user.set_password(password)
            user.save()

            # How to auth and log to the user
            # return User objects if credentials are correct
            # authenticate : check if the u and the pk are in db
            user = authenticate(username=username, password=password)
            if user is not None :
                if user.is_active :
                    #how to log in : just like that
                    login(request, user)
                    # refer to them
                    #request.user.username ...
                    return redirect('music:index')
                else :
                    return logout(request) 

        return render(request, self.template_name, {'form': form})  

project1/music/templates/music/Error404.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Error404</title>
</head>
<body>
    <h1>Protected page</h1>
</body>
</html>

project1/music/templates/music/album_form.html
{% extends 'music/layout.html'%}
{% block title %} Add a new album {% endblock %}
{% block album_active %} active {% endblock %}

{% block body %}

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <form class="form-horizontal" action="" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% include 'music/form-template.html' %}
                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                            <button type="submit" class="btn btn-success">Submit</button>  
                        </div>
                    </div>

                </form>
            </div>

        </div>
    </div>
</div>
{% endblock %}

project1/music/templates/music/detail.html
{% extends 'music/layout.html'%}
{% block title %} Album details {% endblock %}
{% block body %}

    {% load static %}
    {% static "" as baseUrl %}
    <img src="{{ baseUrl }}/{{ album.album_logo }}" style="width: 250px"></img>


    <h1 style="color: blue"> {{album.album_title}} </h1>
    <h3 style="color: red"> {{album.artist}} </h3>


    {% for song in album.song_set.all%}     
        <li style="font-size: 1.2em; color:oldlace">
            {{song.song_title}}.{{song.file_type}}
        </li>
    {% endfor%}

{% endblock %}

project1/music/templates/music/details.html
{% extends 'music/layout.html'%}
{% block title %} Album details {% endblock %}
{% block body %}

    {% load static %}
    {% static "" as baseUrl %}
    <img src="{{ baseUrl }}/{{ album.album_logo }}" style="width: 250px"></img>


    <h3 style="color: red"> {{album.artist}} </h3>


    {% for song in album.song_set.all%}     
        <li style="font-size: 1.2em; color:blue">
            {{song.song_title}}.{{song.file_type}}
        </li>
    {% endfor%}

{% endblock %}

project1/music/templates/music/form-template.html
{% for field in form %}
 <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <span class="text-danger small">{{ field.errors }}</span> 
    </div>
    <label class="control-label col-sm-2">{{ field.label_tag }}</label>
    <div class="control-label col-sm-2">
        {{ field }}
    </div>
 </div>
{% endfor %}

project1/music/templates/music/index.html
{% extends 'music/layout.html'%}
{% block body %}

    <div>
        {% for album in object_list %} 
            <div style="font-size: 1em; display: inline-block">
                {% load static %}
                {% static "" as baseUrl %}
                <!-- image -->
                <img src="{{ baseUrl }}/{{ album.album_logo }}" style="width: 250"></img>

                <!-- Details button -->
                <a href="{% url 'music:details' album.id%}" style="display: inline">
                    <h3 style="color: red">{{album.album_title}} : {{album.id}}$</h3>
                </a>

                <!-- update button -->
                <form action="{% url 'music:album-update' album.id%}" style="display: inline">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-default btn-sm">
                            <span class="glyphicon glyphicon-pencil"></span>
                        </button>
                </form>

                <!-- Delete button -->
                <form action="{% url 'music:album-delete' album.id%}" method="POST" style="display: inline;">
                    {% csrf_token %}
                    <input type="hidden" name="album_id" value="{{ album.id }}"/>
                    <button type="submit" class="btn btn-default btn-sm">
                        <span class="glyphicon glyphicon-trash"></span>
                    </button>
                </form>
                &nbsp;
            </div>
            &nbsp;
            
        {% endfor %}
        </div>

{% endblock %}

project1/music/templates/music/layout.html
<! DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %} Vibes {% endblock %} </title>
        <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <link rel="stylesheet" type="text/css" href='https://fonts.googleapis.com/css?family=Satisfy'>
        <script scr="http://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        <script scr="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

        <!-- Load the path to your static file-->
        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}" />
        <!--link href="./asset/css/bootstrap.min.css" rel="stylesheet"-->

        <nav class="navbar navbar-inverse">
            <div class="container-fluid">
                <!-- Header-->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>

                <!-- Items-->
                <div class="collapse navbar-collapse">
                    <a class="navbar-brand" href="/posts/">Home</a>
                    <ul class="nav navbar-nav">
                        <li class="nav navbar-nav">
                            <a href="{% url 'music:index' %}">
                                <span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp;Albums
                            </a>
                        </li>
                        <li class="nav navbar-nav">
                                <a href="{% url 'music:details' 1%}">
                                    <span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp;Songs
                                </a>
                        </li>
                    </ul>
                    <form class="navbar-form navbar-left" role="search" method="GET" action="#">
                        <div class="form-group">
                            <input type="text" class="fomr-control" name="q" value="">
                        </div>
                        <button type="submit" class="btn btn-default">Search</button>
                    </form>
                    
                    <ul class="nav navbar-nav navbar-right">
                        <li class="">
                            <a href="{% url 'music:album-add' %}">
                                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Album
                            </a>
                        </li>
                        <li class="">
                                <a href="{% url 'music:register' %}">
                                    <span class="glyphicon glyphicon-registration-mark" aria-hidden="true"></span>&nbsp; Register
                                </a>
                        </li>
                        <li class="">
                                <a href="/accounts/logout/">
                                    <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                                </a>
                        </li>
                    </ul>
                </div>

            </div>
        </nav>

        <title>Music app</title>    
    </head>
<body>
   
    {% block body %}
    {% endblock %}  
    
</body>
</html>

project1/music/templates/music/registration_form.html
{% extends 'music/layout.html'%}
{% block title %} Register {% endblock %}

{% block body %}

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <h3>Create a new account:</h3>
                <form class="form-horizontal" action="" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% include 'music/form-template.html' %}
                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                            <button type="submit" class="btn btn-success">Submit</button>  
                        </div>
                    </div>

                </form>
            </div>

        </div>
    </div>
</div>
{% endblock %}