project1/ApiGeo/urls.py
from django.urls import path
from django.conf.urls import url

from . import views

app_name = 'ApiGeo'

urlpatterns = [
    path('', views.home, name='home'),
    url(r'^index/$', views.index, name='index'),
    url(r'^filter/$', views.FilterListView.as_view(), name='filter'),
    url(r'^git/$', views.git, name='git')

]

project1/music/urls.py
from django.conf.urls import url
from . import views 
app_name = 'music'

urlpatterns = [
    #/music/
    #url(r'^$', views.index, name='index'),
    url(r'^album$', views.IndexView.as_view(), name='index'),
    url(r'^$', views.IndexView.as_view(), name='index'),

    #/music/<album_id>
    url(r'^(?P<pk>[0-9]+)/$', views.DetailsView.as_view(), name='details'),

    # /music/album/add/
    url(r'album/add/$', views.AlbumCreate.as_view(), name='album-add'),
    # /music/album/id/
    url(r'album/(?P<pk>[0-9]+)/$', views.AlbumUpdate.as_view(), name='album-update'),
    # /music/album/pk/delete
    url(r'album/(?P<pk>[0-9]+)/delete/$', views.AlbumDelete.as_view(), name='album-delete'),

    # Authenticate
    url(r'^register$', views.UserFormView.as_view(), name='register'),

];

project1/project1/urls.py
from django.contrib import admin
from django.conf.urls import url, include

from rest_framework.urlpatterns import format_suffix_patterns
from stock import views


urlpatterns = [
    url('admin/', admin.site.urls),
    url(r'^$', include('posts.urls')),
    url(r'^posts/', include('posts.urls')),
    url(r'^music/', include('music.urls')),
    url(r'^stock/', views.StockList.as_view()),
    url(r'^ApiGeo/', include('ApiGeo.urls')),
    url('accounts/', include('django.contrib.auth.urls'))
]

urlpatterns = format_suffix_patterns(urlpatterns)

project1/ApiGeo/models.py
from django.db import models

# Create your models here.

project1/ApiGeo/views.py
from django.shortcuts import render
import requests
import re

from music.models import Album
from stock.serializers import AlbumSerializer
from rest_framework import generics, filters
####
from rest_framework.filters import SearchFilter
from rest_framework import status
from rest_framework.response import Response



def index(request):
    search = request.GET['search']
    context = {
        'search': search
    }
    return render(request, 'ApiGeo/index.html')


'''
def index(request):
    if 'search' in request.GET:
        search = request.GET['search']
        context = {
            'search': search
        }
        url = 'http://127.0.0.1:8000/stock/'
        response = requests.get(url)
        search_result = response.json()
        p = re.compile(search, re.IGNORECASE)
        d = {'k': []}
        """
        if search in search_result:
            d['val'] = search
            return render(request, 'core/home2.html', d)
        """
        for r in search_result:
            if p.match(r['artist']):
                d['k'].append(r['artist'])
                #d[r['id']] = r['artist']
                return render(request, 'ApiGeo/index.html', context)

    #return render(request, 'core/home2.html')
    return render(request, 'ApiGeo/index.html')


'''



class FilterListView(generics.ListAPIView):
    queryset = Album.objects.all().filter(artist = "Taylor Swift")
    #queryset = Album.objects.all()
    serializer_class = AlbumSerializer
    filter_backends = (filters.OrderingFilter,)
    filter_fields = ('artist')
    ordering_fields = ('artist','id')


def git(request):
    search_result = {}
    if 'username' in request.GET:
        username = request.GET['username']
        url = 'https://api.github.com/users/%s' % username
        response = requests.get(url)
        search_was_successful = (response.status_code == 200)  # 200 = SUCCESS
        search_result = response.json()
        search_result['success'] = search_was_successful
        search_result['rate'] = {
            'limit': response.headers['X-RateLimit-Limit'],
            'remaining': response.headers['X-RateLimit-Remaining'],
        }
    return render(request, 'core/github.html', {'search_result': search_result})



def home(request):
    ip_address = request.META.get('HTTP_X_FORWARDED_FOR', '')
    response = requests.get('http://freegeoip.net/json/%s' % ip_address)
    geodata = response.json()
    return render(request, 'core/home.html', {
        'ip': 1,#geodata['ip'],
        'country': geodata['country_name'],
        'latitude': geodata['latitude'],
        'longitude': geodata['longitude'],
        'api_key': 'AIzaSyC68MXKBttY-pAMdwotJ4npNuZh7dF4AOw'  # Don't do this! This is just an example. Secure your keys properly.
    })

"""
@api_view(['GET', 'POST'])
def index(request):
    
     #   List all code snippets, or create a new snippet.
    
    if request.method == 'GET':
        snippets = Album.objects.all()
        serializer = AlbumSerializer(snippets, many=True)
        return Response(serializer.data)

    elif request.method == 'POST':
        serializer = AlbumSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

"""

project1/ApiGeo/templates/core/github.html
<h2>GitHub API</h2>
  <form method="get">
    <input type="text" name="username">
    <button type="submit">search on github</button>
  </form>
  {% if search_result %}
    {% if search_result.success %}
      <p>
        <strong>{{ search_result.name|default_if_none:search_result.login }}</strong> has
        <strong>{{ search_result.public_repos }}</strong> public repositories.
      </p>
    {% else %}
      <p><em>{{ search_result.message }}</em></p>
    {% endif %}
    <p>Rate limit: {{ search_result.rate.remaining }}/{{ search_result.rate.limit }}</p>
  {% endif %}

project1/ApiGeo/templates/core/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="x-ua-compatible" content="IE=edge">
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script>
    google.charts.load('current', { 'packages': ['map'] });
    google.charts.setOnLoadCallback(drawMap);

    function drawMap() {
      var data = google.visualization.arrayToDataTable([
        ['Country', 'Population'],
        ['China', 'China: 1,363,800,000'],
        ['India', 'India: 1,242,620,000'],
        ['US', 'US: 317,842,000'],
        ['Indonesia', 'Indonesia: 247,424,598'],
        ['Brazil', 'Brazil: 201,032,714'],
        ['Pakistan', 'Pakistan: 186,134,000'],
        ['Chad', 'Chad: 14,450,000'],
        ['Bangladesh', 'Bangladesh: 152,518,015'],
        ['Russia', 'Russia: 146,019,512'],
        ['Japan', 'Japan: 127,120,000']
      ]);

    var options = {
      showTooltip: true,
      showInfoWindow: true
    };

    var map = new google.visualization.Map(document.getElementById('chart_div'));

    map.draw(data, options);
    };
    </script>

    <title>Ali G</title>
</head>
<body>
    <div style="width:1000px">
        <h2>GEO API : MaK</h2>
        <a href="{% url 'ApiGeo:filter' %}">Filter</a><br/>
        <a href="{% url 'ApiGeo:git' %}">Seach on GitApi</a><br/>
        <a href="{% url 'ApiGeo:index' %}">Seach_on_work</a>

        <div align="center">
            <p>Your ip address is <strong>{{ ip }}</strong>, and you are probably in <strong>{{ country }}</strong> right now.</p>

      <iframe width="600"
              height="450"
              frameborder="0"
              style="border:0"
              src="https://www.google.com/maps/embed/v1/view?center={{ latitude }},{{ longitude }}&zoom=8&key={{ api_key }}"
              allowfullscreen></iframe>
        </div>
        <div id="chart_div"></div>
    </div>

</body>
</html>

project1/ApiGeo/templates/core/home2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {% if d %}
        {% for item in d %}
            <p>
                <strong>{{ item }}</strong> is the G
            </p>
        {% endfor %}
    {% else %}
        <p><em>Unknow value</em></p>
    {% endif %}
</body>
</html>